[package]
name = "pdf-ops"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"
clap = {version="4", features=["derive"]}
lopdf = "0.32"
thiserror = "1"
globset = "0.4"
[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
